<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-0VFP0LG" failures="1" tests="1" name="ieTests" time="37.877" errors="0" timestamp="22 Aug. 2018 07:39:44 GMT">
  <testcase classname="tests.TestSuite" name="testSearchProduct" time="21.721">
    <failure type="java.lang.AssertionError" message="Product1 not found
 expected object to not be null">
      <![CDATA[java.lang.AssertionError: Product1 not found
 expected object to not be null
at tests.TestSuite.testSearchProduct(TestSuite.java:21)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- testSearchProduct -->
</testsuite> <!-- ieTests -->
